---========================---
---== LUA MODULE IMPORTS ==---
---========================---
local debugdraw = require "lua-modules.libs-defold.debug-draw.debug-draw"
local defmath = require "lua-modules.libs-defold.defmath.defmath"
local lume = require "lua-modules.libs-external.lume.lume"
local gui_extra = require "lua-modules.libs-defold.gui_extra.gui_extra"
local monarch = require "lua-modules.libs-defold.monarch.monarch"
local rc = require "lua-modules.libs-defold.rendercam.rendercam"
local cursor = require "lua-modules.libs-defold.defold-input.cursor"
local csv = require "lua-modules.libs-defold.csv-importer.csv-importer"
local c = require "lua-modules.gamedata.constants"
local f = require "lua-modules.libs-self.functions"

---========================---
---========================---

function init(self)
		
	msg.post(".", "acquire_input_focus")
	msg.post("@render:", "use_fixed_fit_projection", { near = -1, far = 1 })	

end

function on_input(self, action_id, action)
	if action_id == hash("touch") and action.pressed then
		print("Touch!")
	end
end


function update(self, dt)
	
	---------------------------------------------------	
	---------------------------------------------------
	---------============= DEBUG =============---------
	---------------------------------------------------
	---------------------------------------------------

	debug_pos_x = 10
	debug_pos_y = 900
	debug_pos_y_plus = 15
	
end


function on_message(self, message_id, message, sender)

end
	